/**
 * Kundali Matching (Ashtakoot Guna Milan) service.
 *
 * Dispatches to Prokerala's real matching endpoint when configured (same
 * ASTROLOGY_PROVIDER=prokerala + PROKERALA_CLIENT_ID/SECRET as the kundali
 * seam — see ./config.ts), falling back to the deterministic mock otherwise.
 * Never computes this with an LLM.
 *
 * Real endpoint verified against Prokerala's OpenAPI spec (Aug 2026):
 *   GET https://api.prokerala.com/v2/astrology/kundli-matching/advanced
 *   params: ayanamsa, girl_coordinates, girl_dob, boy_coordinates, boy_dob, language
 *   ("_dob" is a full ISO 8601 datetime with UTC offset, not just a date.)
 * https://api.prokerala.com/spec/astrology.v2.yaml
 */

import { isProkeralaConfigured } from "./config";
import { resolveBirthLocation } from "./geocode";
import { coordsParam, prokeralaGet } from "./providers/prokerala-client";

export interface MatchPerson {
  name: string;
  dateOfBirth: string; // YYYY-MM-DD
  timeOfBirth: string; // HH:mm
  placeOfBirth: string;
  /** See BirthDetails.timeUnknown in @/types — same 12:00-noon fallback convention. */
  timeUnknown?: boolean;
}

export interface Koota {
  key: string;
  label: string; // English
  hindi: string; // Devanagari
  got: number;
  max: number;
  note: string;
}

export interface MangalCheck {
  compatible: boolean;
  summary: string;
}

export interface MatchResult {
  totalGot: number; // out of 36
  totalMax: number; // 36
  percent: number; // 0–100
  verdict: string; // e.g. "Excellent match"
  kootas: Koota[];
  mangal: MangalCheck;
  recommendation: string;
}

// The 8 kootas and their classical maximum points (sum = 36).
const KOOTA_DEFS: Omit<Koota, "got" | "note">[] = [
  { key: "varna", label: "Varna", hindi: "वर्ण", max: 1 },
  { key: "vashya", label: "Vashya", hindi: "वश्य", max: 2 },
  { key: "tara", label: "Tara", hindi: "तारा", max: 3 },
  { key: "yoni", label: "Yoni", hindi: "योनि", max: 4 },
  { key: "maitri", label: "Graha Maitri", hindi: "ग्रह मैत्री", max: 5 },
  { key: "gana", label: "Gana", hindi: "गण", max: 6 },
  { key: "bhakoot", label: "Bhakoot", hindi: "भकूट", max: 7 },
  { key: "nadi", label: "Nadi", hindi: "नाड़ी", max: 8 },
];

const KOOTA_NOTES: Record<string, string> = {
  varna: "Spiritual & ego compatibility.",
  vashya: "Mutual attraction and control.",
  tara: "Health & destiny compatibility.",
  yoni: "Physical & intimate compatibility.",
  maitri: "Mental & intellectual bonding.",
  gana: "Temperament & behaviour.",
  bhakoot: "Love, finances & family welfare.",
  nadi: "Health of progeny & genes.",
};

/**
 * What a strong vs. weak score in each koota classically signifies. Shown
 * per-row so the breakdown explains itself instead of leaving the reader to
 * interpret a bare "3/8". Purely classical Jyotish reference text keyed to
 * the score band — no interpretation is generated by a model.
 */
const KOOTA_MEANING: Record<string, { strong: string; weak: string }> = {
  varna: {
    strong: "Work ethic and sense of duty align well.",
    weak: "Different values around ego and duty — mutual respect must be worked at consciously.",
  },
  vashya: {
    strong: "Natural mutual attraction and easy give-and-take.",
    weak: "One partner may tend to dominate; conscious balance is advised.",
  },
  tara: {
    strong: "Birth stars support each other's fortune and health.",
    weak: "Star compatibility is weak — traditionally addressed with Nakshatra shanti.",
  },
  yoni: {
    strong: "Good physical and intimate compatibility.",
    weak: "Differing physical temperaments; patience and open communication matter.",
  },
  maitri: {
    strong: "Strong mental and intellectual friendship — the basis of long companionship.",
    weak: "Mental wavelengths differ; shared interests need deliberate cultivation.",
  },
  gana: {
    strong: "Temperaments are well suited day to day.",
    weak: "Different natures (deva/manushya/rakshasa gana) — friction is possible under stress.",
  },
  bhakoot: {
    strong: "Supports prosperity, family harmony and emotional security.",
    weak: "Bhakoot dosha — classically significant for finances and family welfare; remedies are commonly prescribed.",
  },
  nadi: {
    strong: "Excellent — the most heavily weighted koota, supporting health of progeny.",
    weak: "Nadi dosha, the most serious of the eight. A qualified astrologer should assess cancellation (Nadi dosha parihara) before proceeding.",
  },
};

/** Short one-line summary of what a koota governs, independent of provider text. */
export function kootaSummary(key: string): string {
  return KOOTA_NOTES[key] ?? "";
}

export type KootaBand = "strong" | "moderate" | "weak";

export function kootaBand(got: number, max: number): KootaBand {
  const r = max > 0 ? got / max : 0;
  if (r >= 0.75) return "strong";
  if (r >= 0.4) return "moderate";
  return "weak";
}

export function kootaMeaning(key: string, got: number, max: number): string {
  const m = KOOTA_MEANING[key];
  if (!m) return "";
  return kootaBand(got, max) === "weak" ? m.weak : m.strong;
}

/** What the total actually means, in the traditional 36-guna framing. */
export function scoreGuidance(totalGot: number): string {
  if (totalGot >= 32) return "An exceptional union by classical standards — such scores are rare.";
  if (totalGot >= 25) return "Considered a very auspicious match. Traditionally proceeds without remedial requirements.";
  if (totalGot >= 18) return "Above the classical minimum of 18 gunas — an acceptable match that most families proceed with.";
  if (totalGot >= 14) return "Below the traditional threshold of 18. Not a rejection — many such marriages are performed after remedies and a detailed chart reading.";
  return "Well below the classical threshold. A full chart-to-chart reading (not just guna count) is strongly advised before any decision.";
}

const VERDICTS: [number, string][] = [
  [80, "Excellent match"],
  [65, "Very good match"],
  [50, "Acceptable match"],
  [0, "Needs remedial consultation"],
];

function verdictFor(percent: number): string {
  return VERDICTS.find(([t]) => percent >= t)![1];
}

function recommendationFor(percent: number, kootas: Koota[]): string {
  const lowKoota = kootas.reduce((min, k) => (k.got / k.max < min.got / min.max ? k : min));
  return percent >= 65
    ? `A strong union. ${lowKoota.got / lowKoota.max < 0.6 ? `${lowKoota.label} koota is on the lower side — a remedial puja at Ayodhya is recommended before finalising.` : "Auspicious to proceed with an astrologer-confirmed muhurat."}`
    : "Guna score is below the recommended threshold. Consult an Ayodhya-verified astrologer for a detailed reading and remedies.";
}

// --- Public entry point ---------------------------------------------------------

export async function matchKundali(bride: MatchPerson, groom: MatchPerson, locale = "en"): Promise<MatchResult> {
  if (!isProkeralaConfigured()) return mockMatchKundali(bride, groom);
  try {
    return await prokeralaMatchKundali(bride, groom, locale);
  } catch (err) {
    console.error("[matching] Prokerala provider failed, falling back to mock:", err);
    return mockMatchKundali(bride, groom);
  }
}

// --- Real provider ----------------------------------------------------------------

interface GunaEntry { id?: string; name?: string; obtained_points?: number; maximum_points?: number; description?: string; }
interface MangalDoshaDetails { has_dosha?: boolean; dosha_type?: string; description?: string; }
interface KundliMatchingData {
  guna_milan?: { total_points?: number; maximum_points?: number; guna?: GunaEntry[] };
  girl_mangal_dosha_details?: MangalDoshaDetails;
  boy_mangal_dosha_details?: MangalDoshaDetails;
  message?: { type?: string; description?: string };
}

/** Fuzzy-maps Prokerala's koota name (e.g. "Graha Maitri Koot") to our internal key. */
function matchKootaKey(name: string): string | null {
  const n = name.toLowerCase();
  if (n.includes("varna")) return "varna";
  if (n.includes("vasya") || n.includes("vashya")) return "vashya";
  if (n.includes("tara")) return "tara";
  if (n.includes("yoni")) return "yoni";
  if (n.includes("maitri")) return "maitri";
  if (n.includes("gana")) return "gana";
  if (n.includes("bhakoot") || n.includes("bhkoot")) return "bhakoot";
  if (n.includes("nadi")) return "nadi";
  return null;
}

async function prokeralaMatchKundali(bride: MatchPerson, groom: MatchPerson, locale: string): Promise<MatchResult> {
  const [girl, boy] = await Promise.all([
    resolveBirthLocation(bride.placeOfBirth, bride.dateOfBirth, bride.timeOfBirth, bride.timeUnknown),
    resolveBirthLocation(groom.placeOfBirth, groom.dateOfBirth, groom.timeOfBirth, groom.timeUnknown),
  ]);

  const data = await prokeralaGet<KundliMatchingData>("/v2/astrology/kundli-matching/advanced", {
    girl_coordinates: coordsParam(girl.location.latitude, girl.location.longitude),
    girl_dob: girl.datetime,
    boy_coordinates: coordsParam(boy.location.latitude, boy.location.longitude),
    boy_dob: boy.datetime,
    language: locale === "hi" ? "hi" : "en",
  });

  const gunaByKey = new Map<string, GunaEntry>();
  for (const g of data.guna_milan?.guna ?? []) {
    const key = g.name ? matchKootaKey(g.name) : null;
    if (key) gunaByKey.set(key, g);
  }

  const kootas: Koota[] = KOOTA_DEFS.map((def) => {
    const g = gunaByKey.get(def.key);
    return {
      ...def,
      got: g?.obtained_points ?? 0,
      max: g?.maximum_points ?? def.max,
      note: g?.description || KOOTA_NOTES[def.key],
    };
  });

  const totalMax = data.guna_milan?.maximum_points ?? 36;
  const totalGot = data.guna_milan?.total_points ?? kootas.reduce((s, k) => s + k.got, 0);
  const percent = Math.round((totalGot / totalMax) * 100);
  const verdict = data.message?.type || verdictFor(percent);

  const girlManglik = Boolean(data.girl_mangal_dosha_details?.has_dosha);
  const boyManglik = Boolean(data.boy_mangal_dosha_details?.has_dosha);
  const mangalCompatible = girlManglik === boyManglik; // traditional rule: both or neither
  const mangal: MangalCheck = mangalCompatible
    ? { compatible: true, summary: girlManglik ? "Both partners are Manglik — the doshas cancel each other out." : "Neither partner is Manglik — no remedy required." }
    : {
        compatible: false,
        summary: `${girlManglik ? "The bride" : "The groom"} is Manglik and the other is not. A Mangal Shanti puja is advised before fixing a date.`,
      };

  return {
    totalGot,
    totalMax,
    percent,
    verdict,
    kootas,
    mangal,
    recommendation: data.message?.description || recommendationFor(percent, kootas),
  };
}

// --- Mock provider (keyless fallback) ----------------------------------------------

/** Deterministic hash so the same two people always yield the same result. */
function hash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

async function mockMatchKundali(bride: MatchPerson, groom: MatchPerson): Promise<MatchResult> {
  const seed = hash(
    `${bride.name}|${bride.dateOfBirth}|${bride.timeOfBirth}|${groom.name}|${groom.dateOfBirth}|${groom.timeOfBirth}`,
  );

  const kootas: Koota[] = KOOTA_DEFS.map((k, i) => {
    // spread the seed across kootas; bias toward higher scores for a pleasant demo
    const r = (seed >> (i * 3)) & 0xff;
    let got = Math.round((r / 255) * k.max);
    if (got === 0 && k.max > 1) got = 1; // avoid all-zero rows in the mock
    return { ...k, got, note: KOOTA_NOTES[k.key] };
  });

  const totalGot = kootas.reduce((s, k) => s + k.got, 0);
  const totalMax = 36;
  const percent = Math.round((totalGot / totalMax) * 100);
  const verdict = verdictFor(percent);

  const mangalCompatible = ((seed >> 24) & 1) === 1;
  const mangal: MangalCheck = mangalCompatible
    ? { compatible: true, summary: "Both charts are Manglik-compatible — no remedy required." }
    : {
        compatible: false,
        summary: "A Mangal Dosha mismatch is present. A Mangal Shanti puja is advised before fixing a date.",
      };

  return { totalGot, totalMax, percent, verdict, kootas, mangal, recommendation: recommendationFor(percent, kootas) };
}
